// Package scan performs bounded, non-executing static repository inspection.
package scan

import "github.com/Kevin-Umali/repyy/internal/model"

// BuiltinRulesVersion identifies the behavioral rule revision.
const BuiltinRulesVersion = "2026.09.26"

// BuiltinRules returns a newly compiled copy of the embedded behavioral rules.
func BuiltinRules() []Rule {
	const review = "Inspect the surrounding code and remove the behavior if it is not essential."
	const block = "Do not run the repository. Verify the source and intent in an isolated environment."
	rules := []Rule{
		{ID: "EXEC-001", Category: "dynamic-execution", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Dynamic code execution primitive", Pattern: `(?i)(\beval\s*\(|\bnew\s+Function\s*\(|\bFunction\s*\(|\bexecScript\s*\(|\bvm\.(runInNewContext|runInThisContext)|\bnew\s+vm\.Script\s*\()`, Remediation: review},
		{ID: "EXEC-002", Category: "process-execution", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Operating-system command execution", Pattern: `(?i)(\b(?:execSync|execFileSync|execFile|spawnSync|spawn)\s*\(|\bchild_process\.(?:exec|execSync|execFile|execFileSync|spawn|spawnSync)\s*\(|Runtime\.getRuntime\(\)\.exec|ProcessBuilder\s*\(|subprocess\.(run|Popen|call)|os\.system\s*\(|Kernel\.(system|exec)\s*\()`, Remediation: review},
		{ID: "EXEC-004", Category: "process-capability", Severity: model.SeverityLow, Confidence: model.ConfidenceMedium, Description: "Process-execution API is imported", Pattern: `(?i)(from\s+["']node:child_process["']|require\s*\(\s*["'](?:node:)?child_process["']\s*\)|from\s+subprocess\s+import|import\s+subprocess\b)`, Globs: []string{"*.js", "*.cjs", "*.mjs", "*.jsx", "*.ts", "*.tsx", "*.py"}, Remediation: "Confirm that every process invocation uses fixed commands and arguments."},
		{ID: "EXEC-005", Category: "encoded-execution", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "PowerShell executes an encoded command", Pattern: `(?i)(?:powershell|pwsh)(?:\.exe)?[^\n]{0,240}\s-(?:e|en|enc|enco|encod|encode|encoded|encodedc|encodedco|encodedcom|encodedcomm|encodedcomma|encodedcomman|encodedcommand)\b`, Remediation: block},
		{ID: "EXEC-006", Category: "proxy-execution", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "Windows system utility can proxy execution or download content", Pattern: `(?i)\b(?:mshta(?:\.exe)?\s+(?:https?://|javascript:|vbscript:)|rundll32(?:\.exe)?\s+[^\n]{0,240}(?:javascript:|#\d+|,\s*[A-Za-z_$][\w$]*)|regsvr32(?:\.exe)?\s+[^\n]{0,240}(?:/s|/i:)[^\n]{0,240}(?:https?://|scrobj\.dll)|certutil(?:\.exe)?\s+[^\n]{0,240}-(?:urlcache|decode)|bitsadmin(?:\.exe)?\s+[^\n]{0,240}/transfer)`, Remediation: block},
		{ID: "EXEC-003", Category: "dynamic-execution", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Browser or timer string execution primitive", Pattern: `(?i)(set(?:Timeout|Interval)\s*\(\s*["']|document\.write\s*\(|window\.(eval|navigate|open)\s*\()`, Globs: []string{"*.js", "*.cjs", "*.mjs", "*.jsx", "*.ts", "*.tsx", "*.html", "*.htm"}, Remediation: review},
		{ID: "OBFS-001", Category: "encoded-payload", Severity: model.SeverityMedium, Confidence: model.ConfidenceMedium, Description: "Long base64-like payload", Pattern: `[A-Za-z0-9+/]{120,}={0,2}`, Remediation: review},
		{ID: "OBFS-002", Category: "string-obfuscation", Severity: model.SeverityMedium, Confidence: model.ConfidenceMedium, Description: "String decoding or character-code construction", Pattern: `(?i)(atob\s*\(|unescape\s*\(|fromCharCode\s*\(|Buffer\.from\s*\(|bytes\.fromhex\s*\(|base64\.(b64decode|decodebytes)|pack\s*\(\s*["']H\*)`, Remediation: review},
		{ID: "OBFS-003", Category: "string-obfuscation", Severity: model.SeverityMedium, Confidence: model.ConfidenceLow, Description: "Dense hexadecimal or Unicode escape sequence", Pattern: `(?i)((\\x[0-9a-f]{2}){4,}|(\\u[0-9a-f]{4}){3,})`, Remediation: review},
		{ID: "OBFS-006", Category: "string-obfuscation", Severity: model.SeverityMedium, Confidence: model.ConfidenceMedium, Description: "Runtime string reversal or computed global access", Pattern: `(?i)(\.split\s*\(\s*["']{2}\s*\)\s*\.reverse\s*\(\s*\)\s*\.join\s*\(\s*["']{2}\s*\)|(?:window|globalThis|global)\s*\[\s*["'][^"']+["']\s*\+\s*["'][^"']+["']\s*\])`, Globs: []string{"*.js", "*.cjs", "*.mjs", "*.jsx", "*.ts", "*.tsx"}, Remediation: review},
		{ID: "OBFS-007", Category: "string-obfuscation", Severity: model.SeverityMedium, Confidence: model.ConfidenceMedium, Description: "Character shuffler associated with generated obfuscators", Pattern: `(?is)charAt\s*\([^)]*%[^)]*\)[\s\S]{0,500}return\s+[A-Za-z_$][A-Za-z0-9_$]*\.join\s*\(`, Globs: []string{"*.js", "*.cjs", "*.mjs", "*.jsx", "*.ts", "*.tsx"}, Remediation: review},
		{ID: "OBFS-008", Category: "prototype-evasion", Severity: model.SeverityMedium, Confidence: model.ConfidenceLow, Description: "Constructor or prototype access can bypass direct-call signatures", Pattern: `(?i)(\[["']constructor["']\]|\.prototype\.constructor\b|\.__proto__\b|\.constructor\s*\()`, Globs: []string{"*.js", "*.cjs", "*.mjs", "*.jsx", "*.ts", "*.tsx"}, Remediation: review},
		{ID: "OBFS-009", Category: "global-access", Severity: model.SeverityMedium, Confidence: model.ConfidenceLow, Description: "Exported router accesses Node global state", Pattern: `(?is)module\.exports\s*=\s*[A-Za-z_$][A-Za-z0-9_$]*[\s\S]{0,900}\bglobal(?:\.|\[)`, Globs: []string{"*.js", "*.cjs"}, Remediation: review},
		{ID: "PROTO-001", Category: "prototype-pollution", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Write to JavaScript prototype internals", Pattern: `(?i)(__proto__|prototype\s*\[|prototype\.[A-Za-z_$][A-Za-z0-9_$]*)\s*=`, Globs: []string{"*.js", "*.cjs", "*.mjs", "*.ts", "*.tsx", "*.jsx"}, Remediation: review},
		{ID: "NET-001", Category: "remote-fetch", Severity: model.SeverityMedium, Confidence: model.ConfidenceLow, Description: "Remote content fetch", Pattern: `(?i)(curl\s+|wget\s+|Invoke-WebRequest|DownloadString\s*\(|https?\.get\s*\(|fetch\s*\(\s*["']https?://|requests\.(get|post)\s*\()`, Remediation: review},
		{ID: "CHAIN-001", Category: "download-execute", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "Remote download piped into a command interpreter", Pattern: `(?i)(curl|wget)[^\n|;]{0,500}(\||;|&&)\s*(sh|bash|zsh|dash|python[0-9.]*|perl|ruby|node|pwsh|powershell)\b`, Remediation: block},
		{ID: "CHAIN-002", Category: "decode-execute", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "Encoded content decoded and executed", Pattern: `(?i)(base64\s+(-d|--decode)|frombase64string|b64decode)[^\n|;]{0,500}(\||;|&&|exec|eval|system|spawn|Popen)`, Remediation: block},
		{ID: "CHAIN-003", Category: "download-execute", Severity: model.SeverityCritical, Confidence: model.ConfidenceMedium, Description: "Downloaded file is made executable and launched", Pattern: `(?i)(curl|wget)[^\n]{0,500}(-o|--output|>)\s*[^\s;&|]+[^\n]{0,300}chmod\s+[+0-9]*x[^\n]{0,300}([;&|]|\s)(\./|/tmp/|/var/tmp/|~/)[^\s;&|]+`, Remediation: block},
		{ID: "CRED-001", Category: "credential-harvesting", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "Access to sensitive credential storage", Pattern: `(?i)(\.ssh/(id_rsa|id_ed25519|config)|\.aws/(credentials|config)|\.config/gcloud|\.kube/config|\.docker/config\.json|Library/Keychains|login\.keychain|wallet\.dat|key4\.db|Login Data)`, Remediation: block},
		{ID: "CRED-002", Category: "credential-harvesting", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "File API reads a sensitive path", Pattern: `(?i)(readFileSync|readFile|createReadStream|open|read_to_string)\s*\([^\n]{0,180}(\.env\b|/etc/(passwd|shadow)|\.ssh/|\.aws/|id_(rsa|ed25519)|\.(pem|key)\b)`, Remediation: block},
		{ID: "ENV-001", Category: "environment-access", Severity: model.SeverityMedium, Confidence: model.ConfidenceLow, Description: "Broad environment-variable access", Pattern: `(?i)(process\.env\b|os\.environ\b|System\.getenv\s*\(|ENV\.to_h|env\s*\|\s*sort|printenv\b)`, Remediation: review},
		{ID: "EXFIL-001", Category: "exfiltration", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "WebSocket or DNS-based data transfer primitive", Pattern: `(?i)(new\s+WebSocket\s*\(|wss?://|dns\.(resolve|lookup)|nslookup\s+|dig\s+[^\n]*\$|Resolve-DnsName)`, Remediation: block},
		{ID: "EXFIL-002", Category: "credential-theft", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Clipboard, cookie, browser-password, or keylogging access", Pattern: `(?i)(clipboard\.(readText|read)|navigator\.clipboard\.read|document\.cookie|cookies\.(getAll|get)|Login Data|key4\.db|keylog(ger|ging)?|SetWindowsHookEx|GetAsyncKeyState|formData\s*\()`, Remediation: block},
		{ID: "NET-002", Category: "suspicious-network", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "Known exfiltration or tunneling service endpoint", Pattern: `(?i)(discord(app)?\.com/api/webhooks/|api\.telegram\.org/bot[^/\s]+/send|pastebin\.com/raw/|\.ngrok(-free)?\.(io|app)|ngrok\.io)`, Remediation: block},
		{ID: "REVSHELL-001", Category: "reverse-shell", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "Reverse or bind shell behavior", Pattern: `(?i)(/dev/tcp/|bash\s+-i\b|nc\s+[^\n]*(\s-e\s|--exec)|ncat\s+[^\n]*(\s-e\s|--exec|--sh-exec)|socat\s+[^\n]*EXEC:|socket\.connect\s*\([^\n]{0,200}(dup2|/bin/sh)|TcpClient\s*\([^\n]{0,200}GetStream|mkfifo\s+[^\n]{0,200}(/dev/tcp/|\bnc\b))`, Remediation: block},
		{ID: "REVSHELL-002", Category: "reverse-shell", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "Language one-liner creates a command shell over a socket", Pattern: `(?i)((python[0-9.]*\s+-c[^\n]{0,300}import\s+socket|perl\s+-e[^\n]{0,300}use\s+Socket|ruby\s+-r\s*socket\s+-e)[^\n]{0,500}(/bin/(ba)?sh|cmd\.exe|dup2|TCPSocket))`, Remediation: block},
		{ID: "BACKDOOR-001", Category: "backdoor", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "Request-controlled input reaches command execution", Pattern: `(?i)((exec|execSync|system|Popen|eval)\s*\([^\n]{0,240}(req\.(query|body|params)|request\.(args|form|json)|params\[[^]]+\])|(req\.(query|body|params)|request\.(args|form|json)|params\[[^]]+\])[^\n]{0,240}(exec|execSync|system|Popen|eval)\s*\()`, Remediation: block},
		{ID: "BACKDOOR-002", Category: "auth-bypass", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Hardcoded authentication bypass or universal credential", Pattern: `(?i)(bypass(Auth|Login)|skip(Auth|Authentication)|auth\s*=\s*(false|0)|password\s*===?\s*["'][^"']+["']|api.?key\s*===?\s*["'][^"']+["'])`, Remediation: review},
		{ID: "MINER-001", Category: "cryptomining", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "Cryptocurrency mining indicator", Pattern: `(?i)(xmrig|stratum\+(tcp|ssl)|cryptonight|coinhive|monero-pool|minerd\b|nanopool|supportxmr|minexmr|pool\.minergate|(?:3333|4444|5555|7777|14444)\b[^\n]{0,80}(stratum|pool))`, Remediation: block},
		{ID: "EVADE-001", Category: "sandbox-evasion", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Sandbox, VM, or CI evasion logic", Pattern: `(?i)(isDocker\s*\(|detect[-_ ]?(vm|sandbox)|VBOX_|VMware|QEMU|CI\s*===?\s*["']true|GITHUB_ACTIONS|process\.ppid|GetTickCount\s*\()`, Remediation: review},
		{ID: "FINGERPRINT-001", Category: "host-fingerprinting", Severity: model.SeverityMedium, Confidence: model.ConfidenceLow, Description: "Host or user fingerprint collection", Pattern: `(?i)(os\.(hostname|userInfo|networkInterfaces)\s*\(|platform\.node\s*\(|whoami\b|uname\s+-a|systeminfo\b|wmic\s+)`, Remediation: review},
		{ID: "IPURL-001", Category: "hardcoded-network", Severity: model.SeverityMedium, Confidence: model.ConfidenceMedium, Description: "URL uses a hardcoded public-looking IP address", Pattern: `(?i)https?://([1-9][0-9]{0,2}\.){3}[0-9]{1,3}([/:]|$)`, Remediation: review},
		{ID: "IMPORT-001", Category: "dynamic-import", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Dynamic import or require assembled at runtime", Pattern: `(?i)(import\s*\(\s*[^"'\s]|require\s*\(\s*[^"'\s]|__import__\s*\(\s*[^"'\s]|Class\.forName\s*\(\s*[^"'\s)])`, Globs: []string{"*.js", "*.cjs", "*.mjs", "*.jsx", "*.ts", "*.tsx", "*.py", "*.java", "*.kt"}, Remediation: review},
		{ID: "IMPORT-002", Category: "remote-import", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "Code imported directly from a remote URL", Pattern: `(?i)import\s*\(\s*["']https?://`, Remediation: block},
		{ID: "UNICODE-001", Category: "unicode-obfuscation", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Invisible or bidirectional Unicode control character", Pattern: `[\x{00AD}\x{200B}\x{200C}\x{200D}\x{202A}-\x{202E}\x{2060}\x{2066}-\x{2069}\x{FEFF}]`, Remediation: review},
		{ID: "IDE-001", Category: "editor-auto-execution", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "Editor configuration can execute a command automatically", Pattern: `(?i)(runOn["']?\s*:\s*["']?folderOpen|task\.allowAutomaticTasks["']?\s*:\s*["']on|initializeCommand|onCreateCommand|updateContentCommand|postCreateCommand|postStartCommand|postAttachCommand|terminal\.integrated\.profiles|beforeLaunchTask|shellCommand)`, Globs: []string{"tasks.json", "settings.json", "devcontainer.json", "*.code-workspace", "*.xml"}, Remediation: block},
		{ID: "IDE-002", Category: "editor-auto-execution", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Project-local editor configuration can execute commands, override tools, or weaken workspace safeguards", Pattern: `(?i)(recommendations\s*"?\s*:\s*\[[^]]*(unknown|untrusted)|(^|\s)(autocmd|makeprg|shell|exrc)\s*[=: ]|vim?:\s*set[^\n]*(shell|makeprg)|terminal\.integrated\.(shell|automationProfile)|python\.defaultInterpreterPath|(?:extensions\.verifySignature|security\.workspace\.trust\.enabled)["']?\s*:\s*false|terminal\.integrated\.allowInUntrustedWorkspace["']?\s*:\s*true)`, Globs: []string{"extensions.json", "settings.json", ".exrc", ".nvimrc", ".nvim.lua", "*.vim", "*.lua"}, Remediation: review},
		{ID: "IDE-003", Category: "editor-extension-recommendation", Severity: model.SeverityLow, Confidence: model.ConfidenceHigh, Description: "Workspace recommends VS Code extensions", Pattern: `(?is)"recommendations"\s*:\s*\[\s*(?:(?://[^\n]*(?:\n|$)|/\*(?:[^*]|\*+[^*/])*\*+/)\s*)*"[a-z0-9][a-z0-9._-]*\.[a-z0-9][a-z0-9._-]*"`, Globs: []string{"extensions.json", "*.code-workspace"}, Remediation: "Review each extension ID and publisher before choosing to install it."},
		{ID: "IDE-004", Category: "editor-extension-installation", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "Repository configuration installs VS Code extensions", Pattern: `(?is)("extensions"\s*:\s*\[\s*(?:(?://[^\n]*(?:\n|$)|/\*(?:[^*]|\*+[^*/])*\*+/)\s*)*"[a-z0-9][a-z0-9._-]*\.[a-z0-9][a-z0-9._-]*"|\bcode(?:\.cmd)?\s+--install-extension(?:=|\s+))`, Globs: []string{"devcontainer.json", "*.sh", "*.bash", "*.zsh", "*.fish", "*.ps1", "*.bat", "*.cmd"}, Remediation: "Verify the extension publisher, identifier, and source before allowing installation."},
		{ID: "IDE-005", Category: "editor-command", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "Workspace task or debug configuration references an executable command", Pattern: `(?i)("command"\s*:\s*(?:"[^"\n]+"|\{)|"(?:preLaunchTask|postDebugTask)"\s*:\s*"[^"\n]+")`, Globs: []string{"tasks.json", "launch.json"}, Remediation: "Inspect the task command, arguments, referenced scripts, and debugger configuration before running it."},
		{ID: "IDE-006", Category: "devcontainer-feature-installation", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "Devcontainer configuration installs reusable features", Pattern: `(?is)"features"\s*:\s*\{\s*(?:(?://[^\n]*(?:\n|$)|/\*(?:[^*]|\*+[^*/])*\*+/)\s*)*"[^"\n]+"\s*:`, Globs: []string{"devcontainer.json"}, Remediation: "Verify each feature source, publisher, version, and install script before creating the development container."},
		{ID: "IMPORT-003", Category: "dynamic-import", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "Node.js internal or global require bypass", Pattern: `(?i)(process\.mainModule\.require|module\.(parent|children\s*\[[^]]+\])\.require|(?:global|globalThis)\.require\s*\(|__non_webpack_require__\s*\()`, Globs: []string{"*.js", "*.cjs", "*.mjs", "*.jsx", "*.ts", "*.tsx"}, Remediation: block},
		{ID: "AGENT-001", Category: "agent-execution", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "AI-agent configuration requests automatic command execution", Pattern: `(?is)(?:["']?(?:hooks?|mcpServers?|auto[-_ ]?run|allow[-_ ]?commands?|dangerously[-_ ]?skip|bypass[-_ ]?permissions?)["']?\s*[:=])[\s\S]{0,1000}["']?(?:command|shell|bash|powershell|execute|run)["']?\s*[:=]`, Globs: []string{"AGENTS.*", "CLAUDE.*", "*.md", "*.mdc", "*.markdown", "*.mdx", "*.json", "*.yaml", "*.yml", "*.toml", ".cursorrules", ".clinerules", ".windsurfrules"}, Remediation: review},
		{ID: "AGENT-002", Category: "prompt-injection", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Instruction attempts to override agent safety or expose secrets", Pattern: `(?i)((ignore|disregard|override|forget)\s+(all\s+|any\s+|the\s+)?(previous|prior|earlier|above|system)\s+instructions?|(?:reveal|show|print|disclose)\s+(your\s+|the\s+)?(system prompt|secrets?|credentials?)|disable (safety|security|permissions?)|exfiltrat(e|ion)|send .*\.ssh|read .*\.env)`, Globs: []string{"AGENTS.*", "CLAUDE.*", "*.md", "*.mdc", "*.markdown", "*.mdx", "*.txt", ".cursorrules", ".clinerules", ".windsurfrules"}, Remediation: block},
		{ID: "CICD-001", Category: "ci-workflow-injection", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "Privileged pull_request_target workflow checks out untrusted pull-request code", Pattern: `(?is)pull_request_target[\s\S]{0,900}ref:\s*\$\{\{\s*github\.event\.pull_request\.(head\.(sha|ref)|head\.repo)`, Globs: []string{"*.yml", "*.yaml"}, Remediation: block},
		{ID: "CICD-002", Category: "ci-secret-exposure", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "CI workflow interpolates untrusted event data into a shell command", Pattern: `(?i)run\s*:[^\n]*\$\{\{\s*github\.event\.(issue|pull_request|comment|review|discussion)[^}]*\}\}`, Globs: []string{"*.yml", "*.yaml"}, Remediation: block},
		{ID: "CICD-003", Category: "ci-workflow-integrity", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "GitHub Action is referenced by a mutable tag or branch", Pattern: `(?m)^\s*-?\s*uses:\s*[^\s@]+@[^\s#]+`, Globs: []string{"*.yml", "*.yaml"}, Remediation: "Pin third-party actions to a reviewed full commit SHA.", MatchScope: "structured", Disposition: model.DispositionHarden},
		{ID: "CICD-004", Category: "ci-secret-exposure", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "CI command sends a secret to an external endpoint", Pattern: `(?is)(curl|wget|Invoke-WebRequest)[^\n]{0,400}\$\{\{\s*secrets\.[^}]+\}\}|\$\{\{\s*secrets\.[^}]+\}\}[^\n]{0,400}(curl|wget|Invoke-WebRequest)`, Globs: []string{"*.yml", "*.yaml"}, Remediation: block},
		{ID: "CICD-005", Category: "ci-workflow-injection", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Non-GitHub CI configuration builds a shell command from change-controlled input", Pattern: `(?i)(CIRCLE_(BRANCH|SHA1)|CI_(COMMIT|MERGE_REQUEST)|CHANGE_(BRANCH|TITLE)|BUILDKITE_(BRANCH|MESSAGE))[^\n]{0,240}(eval|sh\s+-c|bash\s+-c|curl|wget)|(?:eval|sh\s+-c|bash\s+-c)[^\n]{0,240}(CIRCLE_|CI_COMMIT|CHANGE_|BUILDKITE_)`, Globs: []string{".circleci/config.yml", "Jenkinsfile", ".gitlab-ci.yml", "*.gitlab-ci.yml", "pipeline.yml", "pipeline.yaml"}, Remediation: review},
		{ID: "DOCKER-001", Category: "container-risk", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Container configuration exposes host control", Pattern: `(?i)(/var/run/docker\.sock|--privileged\b|network_mode\s*:\s*host|pid\s*:\s*host|cap_add\s*:[\s\S]{0,100}SYS_ADMIN)`, Globs: []string{"Dockerfile", "Dockerfile.*", "docker-compose*.yml", "docker-compose*.yaml", "compose*.yml", "compose*.yaml"}, Remediation: review},
		{ID: "DOCKER-002", Category: "container-download-execute", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "Container build downloads and immediately executes a script", Pattern: `(?i)RUN\s+[^\n]*(curl|wget)[^\n]*(\||&&)\s*(sh|bash|zsh|python|node)\b`, Globs: []string{"Dockerfile", "Dockerfile.*"}, Remediation: block},
		{ID: "DOCKER-003", Category: "container-risk", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Container imports remote content or mounts a sensitive host path", Pattern: `(?i)(^\s*ADD\s+https?://|[-"']?/(etc|root|home)(/|:)[^\n]{0,180}(:/|target:)|source:\s*/(etc|root|home)\b)`, Globs: []string{"Dockerfile", "Dockerfile.*", "docker-compose*.yml", "docker-compose*.yaml", "compose*.yml", "compose*.yaml"}, Remediation: review},
		{ID: "GITHOOK-001", Category: "git-hook", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Executable Git hook or hooks-path override", Pattern: `(?i)(core\.hooksPath|hooksPath\s*=|pre-commit|post-checkout|post-merge|post-rewrite)`, Globs: []string{"config", "*.hook", "pre-commit", "post-checkout", "post-merge", "post-rewrite"}, Remediation: review},
		{ID: "GITMETA-001", Category: "git-metadata", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "Git configuration defines an executable filter or helper", Pattern: `(?i)(credential\.[^\n=]*helper|credential\.helper|core\.(sshCommand|fsmonitor)|filter\.[^\n=]*\.(clean|smudge)|protocol\.[^\n=]*\.allow\s*=\s*always|includeIf\.)`, Globs: []string{"config", "config.worktree", ".gitattributes", "attributes"}, Remediation: block},
		{ID: "GITHOOK-003", Category: "git-hook", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "Repository config installs and runs pre-commit hooks", Pattern: `(?im)^\s*-\s*repo\s*:\s*(?:https?://|ssh://|git@|git://|local\b)`, Globs: []string{".pre-commit-config.yaml", ".pre-commit-config.yml"}, Remediation: "Review hook repositories, pinned revisions, entries, languages, and additional dependencies before installing the hooks."},
		{ID: "NPMRC-001", Category: "package-registry", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "Package manager configuration contains a registry credential", Pattern: `(?i)(_authToken\s*=|_password\s*=|username\s*=|always-auth\s*=\s*true)`, Globs: []string{".npmrc", ".yarnrc", ".yarnrc.yml"}, Remediation: block},
		{ID: "NPMRC-002", Category: "package-registry", Severity: model.SeverityMedium, Confidence: model.ConfidenceMedium, Description: "Custom package registry", Pattern: `(?i)registry\s*[=:]\s*https?://[^\s"']+`, Globs: []string{".npmrc", ".yarnrc", ".yarnrc.yml"}, Remediation: review},
		{ID: "LOCK-001", Category: "lockfile-tampering", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Lockfile resolves a package from a nonstandard URL", Pattern: `(?i)(resolved|resolution)\s*[":= ]+https?://[^\s"']+`, Globs: []string{"package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml", "Pipfile.lock", "poetry.lock", "Gemfile.lock"}, Remediation: review},
		{ID: "TYPOSQUAT-001", Category: "typosquatting", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Dependency resembles a commonly targeted package name", Pattern: `(?i)["'](crossenv|cross-env\.js|lodahs|loadsh|reqeusts?|requsets|colourama|python-dateutil2|urllib-3|beautifulsoup|djago|flaskk|reactt|expres|mongose)["']\s*[:=]`, Globs: []string{"package.json", "requirements*.txt", "pyproject.toml", "Pipfile", "Gemfile"}, Remediation: review},
		{ID: "SOCIAL-001", Category: "social-engineering", Severity: model.SeverityMedium, Confidence: model.ConfidenceMedium, Description: "Instructions pressure the reader to bypass security controls", Pattern: `(?i)(disable|turn off|bypass|ignore)[^\n]{0,80}(antivirus|anti-virus|defender|gatekeeper|security warning|execution policy|permissions?)|run\s+as\s+(administrator|root)[^\n]{0,100}(interview|assessment|task)`, Globs: []string{"README*", "*.md", "*.txt", "*.rst", "*.adoc"}, Remediation: "Do not follow the instruction until the repository and sender are independently verified."},
		{ID: "SOCIAL-002", Category: "social-engineering", Severity: model.SeverityLow, Confidence: model.ConfidenceMedium, Description: "Interview instructions combine urgency with execution pressure", Pattern: `(?i)((interview|assessment|recruiter|hiring)[^\n]{0,160}(urgent|immediately|within\s+[0-9]+\s+(minutes?|hours?)|time.?sensitive)|(urgent|immediately|within\s+[0-9]+\s+(minutes?|hours?)|time.?sensitive)[^\n]{0,160}(interview|assessment|recruiter|hiring))`, Globs: []string{"README*", "*.md", "*.txt", "*.rst", "*.adoc"}, Remediation: "Independently verify the sender and repository; urgency should not override safe review."},
		{ID: "APT-001", Category: "contagious-interview", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "BeaverTail or InvisibleFerret filesystem indicator", Pattern: `(?i)(/|\\)\.n2(/|\\)(pay|bow|mlip)|(/|\\)\.npl\b|(/|\\)(pdown|\.sysinfo)\b`, Remediation: block},
		{ID: "SECRET-001", Category: "secret", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "Private key material", Pattern: `-----BEGIN (RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----`, Remediation: "Revoke or rotate the credential and remove it from repository history."},
		{ID: "SECRET-002", Category: "secret", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "Provider credential pattern", Pattern: `(?i)(AKIA[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9_]{30,}|github_pat_[A-Za-z0-9_]{40,}|sk_live_[A-Za-z0-9]{20,}|SK[0-9a-f]{32}|xox[baprs]-[A-Za-z0-9-]{20,})`, Remediation: "Revoke or rotate the credential and remove it from repository history."},
		{ID: "SECRET-003", Category: "secret", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Generic API key, access token, or client secret assignment", Pattern: `(?i)(api[_-]?key|access[_-]?token|client[_-]?secret)\s*[:=]\s*["'][A-Za-z0-9_./+=-]{16,}["']`, Remediation: "Verify whether this is a real credential; if so, revoke it and remove it from repository history."},
		{ID: "SHELL-001", Category: "shell-persistence", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Shell profile or operating-system startup persistence", Pattern: `(?i)(>>?\s*(~?/)?\.(bashrc|zshrc|profile)|crontab\s+-|schtasks(?:\.exe)?\s+/create|(?:reg(?:\.exe)?\s+add|new-itemproperty)[^\n]{0,240}\\(?:run|runonce)\b|LaunchAgents|launchctl\s+(?:load|bootstrap)|systemctl\s+(?:--user\s+)?enable|\.config/autostart|start menu[\\/]programs[\\/]startup)`, Remediation: block},
		{ID: "PERSIST-001", Category: "system-persistence", Severity: model.SeverityCritical, Confidence: model.ConfidenceHigh, Description: "Command creates a service, daemon, login item, or WMI event subscription", Pattern: `(?i)(\bsc(?:\.exe)?\s+(?:create|config)\b|new-service\b|/library/launchdaemons\b|launchctl\s+(?:bootstrap|load)\s+system\b|(?:__eventfilter|commandlineeventconsumer|__filtertoconsumerbinding)|systemctl\s+(?:--user\s+)?enable\s+[^\n]+\.(?:service|timer)\b|osascript[^\n]{0,300}(?:login item|system events[^\n]{0,120}make login item))`, Remediation: block},
		{ID: "PERSIST-002", Category: "startup-configuration", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "Repository contains an automatically started service, timer, or launchd job", Pattern: `(?i)(^\s*ExecStart\s*=|^\s*OnCalendar\s*=|<key>\s*(?:RunAtLoad|KeepAlive)\s*</key>)`, Globs: []string{"*.service", "*.timer", "*.plist"}, Remediation: "Review the executable, arguments, user, privileges, and activation conditions before installing or enabling this startup configuration."},
		{ID: "AUTORUN-001", Category: "directory-auto-execution", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Directory-entry environment hook can execute repository-controlled commands", Pattern: `(?i)(^|\s)(source(?:_up)?|dotenv|use\s+(?:flake|nix)|layout|path_add|watch_file)\b`, Globs: []string{".envrc"}, Remediation: "Review the complete .envrc before approving it with direnv."},
		{ID: "AUTORUN-002", Category: "development-shell-execution", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "Nix development shell defines a shell hook", Pattern: `(?i)\bshellHook\s*=`, Globs: []string{"shell.nix", "flake.nix"}, Remediation: "Inspect the shellHook before entering the Nix development shell."},
		{ID: "INSTALL-001", Category: "system-installation", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "Setup script installs host packages or global developer tools", Pattern: `(?i)(\b(?:apt(?:-get)?|dnf|yum|zypper)\s+(?:-[^\s]+\s+)*install\b|\bpacman\s+(?:-[^\s]*S[^\s]*|--sync)\b|\b(?:brew|choco|winget|scoop|gem|cargo)\s+install\b|\b(?:python[0-9.]*\s+-m\s+pip|pip[0-9.]*)\s+install\b|\bnpm\s+(?:install|i)\s+(?:-[^\s]+\s+)*(?:-g|--global)\b|\bgo\s+install\s+\S+)`, Globs: []string{"install.*", "setup.*", "bootstrap.*", "provision.*", "*.sh", "*.bash", "*.zsh", "*.fish", "*.ps1", "*.bat", "*.cmd"}, Remediation: "Review package names, sources, versions, and privileges before running the installer."},
		{ID: "FONT-001", Category: "font-installation", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "Script installs or registers fonts on the host", Pattern: `(?i)(addfontresource(?:ex)?[aw]?\s*\(|install-font\b|fontview\.exe|(?:copy|copy-item|cp|install|mv|move-item)[^\n]{0,240}(?:%windir%[\\/]fonts|[a-z]:[\\/]windows[\\/]fonts|%localappdata%[\\/]microsoft[\\/]windows[\\/]fonts|\$env:localappdata[\\/]microsoft[\\/]windows[\\/]fonts|/library/fonts|~/library/fonts|\.local/share/fonts|/usr/(?:local/)?share/fonts)|(?:reg(?:\.exe)?\s+add|new-itemproperty)[^\n]{0,240}\\fonts\b|\bfc-cache(?:\s|$))`, Globs: []string{"*.sh", "*.bash", "*.zsh", "*.fish", "*.ps1", "*.bat", "*.cmd", "*.py", "*.js", "*.ts", "*.go", "*.rs", "*.c", "*.cc", "*.cpp", "*.cs"}, Remediation: "Verify every font file and destination before allowing the script to modify host font stores."},
		{ID: "BUILD-001", Category: "build-command", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "CMake configuration executes an external command", Pattern: `(?i)\b(?:execute_process|add_custom_(?:command|target))\s*\([^)]*\bCOMMAND\b`, Globs: []string{"CMakeLists.txt", "*.cmake"}, Remediation: "Inspect the command, arguments, inputs, and build phase before configuring or building the project."},
		{ID: "BUILD-002", Category: "build-command", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "Meson configuration executes an external command", Pattern: `(?i)\b(?:run_command|custom_target)\s*\(`, Globs: []string{"meson.build", "meson_options.txt"}, Remediation: "Inspect the command and generated outputs before configuring or building the project."},
		{ID: "BUILD-003", Category: "build-command", Severity: model.SeverityMedium, Confidence: model.ConfidenceMedium, Description: "Bazel rule declares a shell command", Pattern: `(?is)\b(?:genrule|repository_rule)\s*\([^)]*\bcmd(?:_bash|_bat|_ps)?\s*=`, Globs: []string{"BUILD", "BUILD.bazel", "WORKSPACE", "WORKSPACE.bazel", "*.bzl"}, Remediation: "Inspect the declared command and its inputs before running Bazel."},
		{ID: "BUILD-004", Category: "build-command", Severity: model.SeverityHigh, Confidence: model.ConfidenceHigh, Description: "Make evaluates a shell command while reading the build file", Pattern: `(?i)\$\(\s*shell\s+[^)]+\)`, Globs: []string{"Makefile", "makefile", "GNUmakefile", "*.mk"}, Remediation: "Inspect the shell expression before invoking Make, including during dry runs and variable expansion."},
		{ID: "UNSERIALIZE-001", Category: "unsafe-deserialization", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Unsafe deserialization primitive", Pattern: `(?i)(unserialize\s*\(|pickle\.loads?\s*\(|yaml\.load\s*\([^\n]*Loader\s*=\s*yaml\.(Loader|UnsafeLoader)|ObjectInputStream\s*\()`, Remediation: review},
		{ID: "PATH-001", Category: "path-traversal", Severity: model.SeverityMedium, Confidence: model.ConfidenceMedium, Description: "Request-controlled path reaches a file operation", Pattern: `(?i)(path\.(join|resolve)|sendFile|readFile|readFileSync|open)\s*\([^\n]{0,180}(req\.|request\.|params\[|query\[)`, Remediation: review},
		{ID: "PY-001", Category: "python-install-hook", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Python package defines installation-time command hooks", Pattern: `(?i)(cmdclass\s*=|class\s+[^\n]*(install|develop|build_ext)[^\n]*\(|setup_requires\s*=)`, Globs: []string{"setup.py", "setup.cfg", "pyproject.toml"}, Remediation: review},
		{ID: "PY-002", Category: "python-dependency-source", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Python dependency is loaded from a URL or VCS source", Pattern: `(?i)(git\+https?://|https?://[^\s]+\.(whl|tar\.gz|zip)|\{\s*(git|url)\s*=)`, Globs: []string{"requirements*.txt", "pyproject.toml", "Pipfile", "setup.py", "setup.cfg"}, Remediation: review},
		{ID: "RUBY-001", Category: "ruby-dependency-source", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Ruby dependency is loaded from a Git or path source", Pattern: `(?i)gem\s+["'][^"']+["'][^\n]*(git:|github:|path:|source:)`, Globs: []string{"Gemfile", "*.gemspec"}, Remediation: review},
		{ID: "GO-001", Category: "go-generate", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "Go source declares a generator command", Pattern: `(?m)^\s*//go:generate\s+.+`, Globs: []string{"*.go"}, Remediation: "Inspect the generator command before running go generate."},
		{ID: "GO-002", Category: "go-module-replacement", Severity: model.SeverityMedium, Confidence: model.ConfidenceMedium, Description: "Go module replaces a dependency source", Pattern: `(?m)^\s*replace\s+[^\n]+=>\s+[^\n]+`, Globs: []string{"go.mod", "go.work"}, Remediation: review},
		{ID: "JVM-001", Category: "jvm-build-execution", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "JVM build configuration invokes an external process", Pattern: `(?i)(Exec\s*\{|commandLine\s+|providers\.exec|exec-maven-plugin|maven-antrun-plugin)`, Globs: []string{"build.gradle", "build.gradle.kts", "pom.xml", "settings.gradle", "settings.gradle.kts"}, Remediation: review},
		{ID: "JVM-002", Category: "jvm-repository", Severity: model.SeverityMedium, Confidence: model.ConfidenceMedium, Description: "JVM build uses a custom dependency repository", Pattern: `(?i)(maven\s*\{[^\n]*url|<repository>|<pluginRepository>)`, Globs: []string{"build.gradle", "build.gradle.kts", "pom.xml", "settings.gradle", "settings.gradle.kts"}, Remediation: review},
		{ID: "PHP-001", Category: "composer-script", Severity: model.SeverityHigh, Confidence: model.ConfidenceMedium, Description: "Composer package defines an installation or update script", Pattern: `(?i)"(pre|post)-(install|update)-cmd"\s*:`, Globs: []string{"composer.json"}, Remediation: review},
		{ID: "RUST-001", Category: "rust-build-script", Severity: model.SeverityMedium, Confidence: model.ConfidenceHigh, Description: "Rust package declares a build script", Pattern: `(?i)^\s*build\s*=\s*["'][^"']+["']`, Globs: []string{"Cargo.toml"}, Remediation: "Inspect build.rs or the referenced build script before compiling."},
	}
	for i := range rules {
		if err := rules[i].Compile(); err != nil {
			panic(err)
		}
	}
	return rules
}
