// repyy-intelgen refreshes metadata for the curated embedded advisory set.
// It is a maintainer tool and is not included in release archives.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/Kevin-Umali/repyy/internal/intel"
)

type advisory struct {
	ID          string          `json:"ghsa_id"`
	Summary     string          `json:"summary"`
	PublishedAt time.Time       `json:"published_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	WithdrawnAt *time.Time      `json:"withdrawn_at"`
	References  []string        `json:"references"`
	Vulnerable  []vulnerability `json:"vulnerabilities"`
}

type vulnerability struct {
	Package struct {
		Ecosystem string `json:"ecosystem"`
		Name      string `json:"name"`
	} `json:"package"`
	Range string `json:"vulnerable_version_range"`
}

func main() {
	output := flag.String("output", "internal/intel/package_metadata_generated.go", "generated Go output")
	flag.Parse()
	if err := run(*output); err != nil {
		fmt.Fprintln(os.Stderr, "repyy-intelgen:", err)
		os.Exit(1)
	}
}

func run(output string) error {
	entries := append([]intel.Package(nil), intel.Packages...)
	sort.Slice(entries, func(i, j int) bool { return entries[i].AdvisoryID < entries[j].AdvisoryID })
	var body bytes.Buffer
	body.WriteString("// Code generated by repyy-intelgen; DO NOT EDIT.\n\npackage intel\n\n")
	body.WriteString("var packageDetailsByAdvisory = map[string]packageDetails{\n")
	for _, entry := range entries {
		if !strings.HasPrefix(entry.AdvisoryID, "GHSA-") {
			continue
		}
		item, err := fetch(entry.AdvisoryID)
		if err != nil {
			return err
		}
		if item.WithdrawnAt != nil {
			return fmt.Errorf("selected advisory %s was withdrawn on %s", item.ID, item.WithdrawnAt.Format(time.DateOnly))
		}
		ranges := make([]string, 0)
		for _, vulnerable := range item.Vulnerable {
			if strings.EqualFold(vulnerable.Package.Ecosystem, entry.Ecosystem) && vulnerable.Package.Name == entry.Name && vulnerable.Range != "" {
				ranges = append(ranges, vulnerable.Range)
			}
		}
		sort.Strings(ranges)
		references := append([]string(nil), item.References...)
		sort.Strings(references)
		fmt.Fprintf(&body, "\t%q: {Description: %q, Added: %q, Modified: %q, Affected: %#v, References: %#v},\n", item.ID, item.Summary, item.PublishedAt.Format(time.DateOnly), item.UpdatedAt.Format(time.DateOnly), ranges, references)
	}
	body.WriteString("}\n")
	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}
	dir := filepath.Dir(output)
	tmp, err := os.CreateTemp(dir, ".repyy-intel-*.go")
	if err != nil {
		return fmt.Errorf("create temporary output: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := tmp.Write(formatted); err != nil {
		tmp.Close()
		return fmt.Errorf("write temporary output: %w", err)
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpName, output); err != nil {
		return fmt.Errorf("replace generated output: %w", err)
	}
	return nil
}

func fetch(id string) (advisory, error) {
	cmd := exec.Command("gh", "api", "-H", "X-GitHub-Api-Version: 2022-11-28", "/advisories/"+id)
	cmd.Env = append(os.Environ(), "GH_PROMPT_DISABLED=1")
	data, err := cmd.Output()
	if err != nil {
		return advisory{}, fmt.Errorf("fetch %s with gh: %w", id, err)
	}
	var item advisory
	if err := json.Unmarshal(data, &item); err != nil {
		return advisory{}, fmt.Errorf("decode %s: %w", id, err)
	}
	if item.ID != id {
		return advisory{}, fmt.Errorf("unexpected advisory id %q for %s", item.ID, id)
	}
	return item, nil
}
